PT-8500: Implement techdebt
VirtoCommerce/vc-module-event-bus pull request #15
Opened 2022-08-15 14:24 UTC by akak1977

## Description
*Don't merge! Still in progress...*
Module rework to resolve tech debt.
## References
### QA-test:
### Jira-link:
https://virtocommerce.atlassian.net/browse/PT-8500
### Artifact URL:

2022-08-29 13:51 UTC, ksavosteev approved these changes, later dismissed

2022-08-29 16:18 UTC, zashchitnik-kuka submitted a review, later dismissed
Language: Fixed and approved

2022-09-02 07:08 UTC, OlegoO requested changes

2022-09-02 07:08 UTC, OlegoO commented on docs/index.md
> +|JsonPathFilter|`JsonPath` filter expression that allows you to additionally filter events that have specific value in the body. If the body with applied `JsonPath` filter does not yield any value, t
Add JsonPathFilter examples, for example send event for Specific Order Status Only

2022-09-02 07:08 UTC, OlegoO commented on docs/index.md
> +|PayloadTransformationTemplate|An optional setting where you can specify a Liquid template to transform event data to a different form. If omitted, null, or an empty string, the event data will be tr
Add several examples for PayloadTransformationTemplate

2022-09-02 07:08 UTC, OlegoO commented on docs/index.md
> +  "name": "string",
Change on example with real data

2022-09-02 07:08 UTC, OlegoO commented on docs/index.md
> +```json
Add example how to use for external health monitoring

2022-09-06 10:03 UTC, merged